[theme]
primaryColor = "#2471c8"
backgroundColor = "#dce8f5"
secondaryBackgroundColor = "#c8d9ed"
textColor = "#0f1c2e"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true
